/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bikeservicecenterproject;

/**
 *
 * @author パワーPower
 */
import javax.swing.*;
import java.awt.*;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;

public class Account extends javax.swing.JFrame {

    String user;
    String pw;
    Connection con;
    Statement stmt;
    String url = "jdbc:mysql://localhost:3306/bikeservicecenter";

    /**
     * Creates new form Account
     */
    public Account() throws SQLException { 
        this("admin","admin");
    }

    public Account(String user, String pw) throws SQLException {
        initComponents();
        this.pw = pw;
        this.user = user;
        System.out.println("Account");
        System.out.println(user);
        System.out.println(pw);
        con = DriverManager.getConnection(url, "root", "");
        String sql = "Select name,contact,address from supervisor where username='" + user + "' AND password='" + pw + "'";
        stmt = con.createStatement();
        if (con != null) {
            ResultSet result=stmt.executeQuery(sql);
            if(result.first()){
                nameLabel.setText(result.getString(1));
                contactLabel.setText(result.getString(2));
                addressLabel.setText(result.getString(3));
            }
        }else{
                System.out.println("Failed to connect to database");
    }
}

/**
 * This method is called from within the constructor to initialize the form.
 * WARNING: Do NOT modify this code. The content of this method is always
 * regenerated by the Form Editor.
 */
@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        changePasswordPanel = new javax.swing.JPanel();
        changePassword = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        contactLabel = new javax.swing.JLabel();
        addressLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        kGradientPanel1 = new com.k33ptoo.components.KGradientPanel();
        jLabel1 = new javax.swing.JLabel();
        ImageLabel = new javax.swing.JLabel();
        registerLabel = new javax.swing.JLabel();
        addRepairLabel = new javax.swing.JLabel();
        makeBillLabel = new javax.swing.JLabel();
        accountUpdateLabel = new javax.swing.JLabel();
        logoutLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setFocusTraversalPolicyProvider(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel2.setText("Profile");

        jLabel5.setText("Name:");

        jLabel6.setText("Contact:");

        changePasswordPanel.setBackground(new java.awt.Color(255, 255, 255));
        changePasswordPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                changePasswordPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                changePasswordPanelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                changePasswordPanelMousePressed(evt);
            }
        });

        changePassword.setBackground(new java.awt.Color(0, 0, 0));
        changePassword.setText("Change Password");
        changePassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                changePasswordMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                changePasswordMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                changePasswordMouseExited(evt);
            }
        });

        javax.swing.GroupLayout changePasswordPanelLayout = new javax.swing.GroupLayout(changePasswordPanel);
        changePasswordPanel.setLayout(changePasswordPanelLayout);
        changePasswordPanelLayout.setHorizontalGroup(
            changePasswordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(changePassword, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        changePasswordPanelLayout.setVerticalGroup(
            changePasswordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(changePasswordPanelLayout.createSequentialGroup()
                .addComponent(changePassword, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        jLabel8.setText("Address:");

        contactLabel.setText("9851065568");

        addressLabel.setText("Swyambhu");

        nameLabel.setText("Rabin Maharjan");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(213, 450, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(changePasswordPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(addressLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(contactLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(144, 450, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(357, 357, 357)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel2)
                .addGap(29, 29, 29)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(contactLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addressLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(changePasswordPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(395, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(389, 0, -1, -1));

        kGradientPanel1.setkEndColor(new java.awt.Color(255, 255, 255));
        kGradientPanel1.setkStartColor(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("D&D Service Center");

        ImageLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ImageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/HomeLogo (2).jpg"))); // NOI18N
        ImageLabel.setToolTipText("");
        ImageLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        registerLabel.setBackground(new java.awt.Color(255, 255, 255));
        registerLabel.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        registerLabel.setForeground(new java.awt.Color(255, 255, 255));
        registerLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        registerLabel.setText("Bike Register");
        registerLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                registerLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                registerLabelMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                registerLabelMouseReleased(evt);
            }
        });

        addRepairLabel.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        addRepairLabel.setForeground(new java.awt.Color(255, 255, 255));
        addRepairLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        addRepairLabel.setText("Add for Repair");
        addRepairLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addRepairLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addRepairLabelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                addRepairLabelMousePressed(evt);
            }
        });

        makeBillLabel.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        makeBillLabel.setForeground(new java.awt.Color(255, 255, 255));
        makeBillLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        makeBillLabel.setText("Make Bill");
        makeBillLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                makeBillLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                makeBillLabelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                makeBillLabelMousePressed(evt);
            }
        });

        accountUpdateLabel.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        accountUpdateLabel.setForeground(new java.awt.Color(255, 255, 255));
        accountUpdateLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        accountUpdateLabel.setText("Account Update");
        accountUpdateLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                accountUpdateLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                accountUpdateLabelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                accountUpdateLabelMousePressed(evt);
            }
        });

        logoutLabel.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        logoutLabel.setForeground(new java.awt.Color(255, 255, 255));
        logoutLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logoutLabel.setText("Log out");
        logoutLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logoutLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logoutLabelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                logoutLabelMousePressed(evt);
            }
        });

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 361, Short.MAX_VALUE)
                .addGap(18, 18, 18))
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap(128, Short.MAX_VALUE)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addRepairLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(registerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(makeBillLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(ImageLabel))
                    .addComponent(accountUpdateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(logoutLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(138, Short.MAX_VALUE))
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(ImageLabel)
                .addGap(30, 30, 30)
                .addComponent(registerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(addRepairLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(makeBillLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(accountUpdateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(logoutLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(kGradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 700));

        setSize(new java.awt.Dimension(1118, 743));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void changePasswordPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_changePasswordPanelMouseEntered
        changePasswordPanel.setBackground(Color.lightGray);  // TODO add your handling code here:
    }//GEN-LAST:event_changePasswordPanelMouseEntered

    private void changePasswordPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_changePasswordPanelMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_changePasswordPanelMousePressed

    private void changePasswordPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_changePasswordPanelMouseExited
        changePasswordPanel.setBackground(Color.white);  // TODO add your handling code here:
    }//GEN-LAST:event_changePasswordPanelMouseExited

    private void registerLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerLabelMouseEntered
        // TODO add your handling code here:
        registerLabel.setForeground(Color.BLACK);
    }//GEN-LAST:event_registerLabelMouseEntered

    private void registerLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerLabelMouseExited
        // TODO add your handling code here:
        registerLabel.setForeground(Color.white);
    }//GEN-LAST:event_registerLabelMouseExited

    private void registerLabelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerLabelMouseReleased
        // TODO add your handling code here:
        this.dispose();
        HomePage frame = null;
        try {
            frame = new HomePage(user, pw);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(HomePage.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(HomePage.class.getName()).log(Level.SEVERE, null, ex);
        }
        frame.setVisible(true);
    }//GEN-LAST:event_registerLabelMouseReleased

    private void addRepairLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addRepairLabelMouseEntered
        // TODO add your handling code here:
        addRepairLabel.setForeground(Color.BLACK);
    }//GEN-LAST:event_addRepairLabelMouseEntered

    private void addRepairLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addRepairLabelMouseExited
        // TODO add your handling code here:
        addRepairLabel.setForeground(Color.white);
    }//GEN-LAST:event_addRepairLabelMouseExited

    private void addRepairLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addRepairLabelMousePressed
        this.dispose();
        AddToRepairPage frame = new AddToRepairPage(user, pw);
        frame.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_addRepairLabelMousePressed

    private void makeBillLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_makeBillLabelMouseEntered
        // TODO add your handling code here:
        makeBillLabel.setForeground(Color.BLACK);
    }//GEN-LAST:event_makeBillLabelMouseEntered

    private void makeBillLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_makeBillLabelMouseExited
        // TODO add your handling code here:
        makeBillLabel.setForeground(Color.white);
    }//GEN-LAST:event_makeBillLabelMouseExited

    private void makeBillLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_makeBillLabelMousePressed
        // TODO add your andling code here:
        this.dispose();
        MakeBill frame = new MakeBill(user, pw);
        frame.setVisible(true);
    }//GEN-LAST:event_makeBillLabelMousePressed

    private void accountUpdateLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accountUpdateLabelMouseEntered
        accountUpdateLabel.setForeground(Color.black);        // TODO add your handling code here:
    }//GEN-LAST:event_accountUpdateLabelMouseEntered

    private void accountUpdateLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accountUpdateLabelMouseExited
        accountUpdateLabel.setForeground(Color.white); // TODO add your handling code here:
    }//GEN-LAST:event_accountUpdateLabelMouseExited

    private void accountUpdateLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accountUpdateLabelMousePressed
        try {
            new Account(user, pw).setVisible(true);
            this.dispose();
            // TODO add your handling code here:
        } catch (SQLException ex) {
            Logger.getLogger(MakeBill.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_accountUpdateLabelMousePressed

    private void logoutLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutLabelMouseEntered
        // TODO add your handling code here:
        logoutLabel.setForeground(Color.BLACK);
    }//GEN-LAST:event_logoutLabelMouseEntered

    private void logoutLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutLabelMouseExited
        // TODO add your handling code here:
        logoutLabel.setForeground(Color.WHITE);
    }//GEN-LAST:event_logoutLabelMouseExited

    private void logoutLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutLabelMousePressed
        // TODO add your handling code here:
//        this.dispose();
//        new LoginPage().setVisible(true);
    }//GEN-LAST:event_logoutLabelMousePressed

    private void changePasswordMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_changePasswordMouseExited
        // TODO add your handling code here:
        changePasswordPanel.setBackground(Color.white);
    }//GEN-LAST:event_changePasswordMouseExited

    private void changePasswordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_changePasswordMouseEntered
        changePasswordPanel.setBackground(Color.LIGHT_GRAY);
        // TODO add your handling code here:
    }//GEN-LAST:event_changePasswordMouseEntered

    private void changePasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_changePasswordMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_changePasswordMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                

}
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Account.class
.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        

} catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Account.class
.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        

} catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Account.class
.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        

} catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Account.class
.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
 try {
            Class.forName("com.mysql.jdbc.Driver");
        

} catch (ClassNotFoundException ex) {
//            Logger.getLogger(LoginPage.class
//.getName()).log(Level.SEVERE, null, ex);
        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Account().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Account.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ImageLabel;
    private javax.swing.JLabel accountUpdateLabel;
    private javax.swing.JLabel addRepairLabel;
    private javax.swing.JLabel addressLabel;
    private javax.swing.JLabel changePassword;
    private javax.swing.JPanel changePasswordPanel;
    private javax.swing.JLabel contactLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private com.k33ptoo.components.KGradientPanel kGradientPanel1;
    private javax.swing.JLabel logoutLabel;
    private javax.swing.JLabel makeBillLabel;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel registerLabel;
    // End of variables declaration//GEN-END:variables
}
