/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bikeservicecenterproject;

import java.awt.Color;
import java.awt.Component;
import java.awt.Container;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.event.KeyEvent;
import java.awt.print.PrinterException;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import java.sql.*;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author パワーPower
 */
public class FMakeBill extends javax.swing.JInternalFrame {
    int serviceId=0;
    int newTotal=0;
    ResultSet rs;
    String url = "jdbc:mysql://localhost:3306/bikeservicecenter";
    Connection con;
    Statement stmt;
    String user;
    String pw;
    DefaultListModel<String> m = new DefaultListModel<>();
    DefaultTableModel dtm;
    Dimension dmsn=new Dimension(700, 900);
    /**
     * /**
     * Creates new form Register
     */
    public FMakeBill() {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection(url, "root", "");
            stmt=con.createStatement();
            initComponents();
            this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
            BasicInternalFrameUI ui = (BasicInternalFrameUI) this.getUI();
            ui.setNorthPane(null);
            getProduct();
            getInfoComplete();
            billData();
            getBillNumber();
            billTable.removeColumn(billTable.getColumnModel().getColumn(0));
            billTable.removeColumn(billTable.getColumnModel().getColumn(0));
            JTableHeader header = productTable.getTableHeader();
            header.setFont(new Font("Times New Roman", Font.BOLD, 18));
            DefaultTableCellRenderer d = ((DefaultTableCellRenderer) productTable.getTableHeader().getDefaultRenderer());
            d.setHorizontalAlignment(JLabel.LEFT);
            completeTable.setShowGrid(true);
            completeTable.setGridColor(Color.BLACK);
            productTable.setShowGrid(true);
            productTable.setGridColor(Color.BLACK);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(FMakeBill.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(FMakeBill.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void billData(){
        try {
            dtm=(DefaultTableModel) billTable.getModel();
            dtm.setRowCount(0);
            JTableHeader header = billTable.getTableHeader();
            header.setFont(new Font("Times New Roman", Font.BOLD, 24));
            DefaultTableCellRenderer d = ((DefaultTableCellRenderer) billTable.getTableHeader().getDefaultRenderer());
            d.setHorizontalAlignment(JLabel.LEFT);
            String sql="Select m.billnumber,m.serviceid,m.ownername,m.numberplate,m.totalprice,m.date,b.bikemodel from bikeinfo as b,makebill as m where m.numberplate=b.numberplate";
            rs=stmt.executeQuery(sql);
            while(rs.next()){
                String bill=rs.getString("billnumber");
                String service=rs.getString("serviceid");
                String ownername=rs.getString("ownername");
                String numberplate=rs.getString("numberplate");
                String totalprice=rs.getString("totalprice");
                String date=rs.getString("date");
                String model=rs.getString("bikemodel");
                dtm=(DefaultTableModel) billTable.getModel();
                String []list={bill,service,ownername,numberplate,model,totalprice,date};
                dtm.addRow(list);
            }
        } catch (SQLException ex) {
            Logger.getLogger(FMakeBill.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
      public void getProduct() {
//        m.removeAllElements();
// 
        try {
            String sql = "Select productname from product";
            rs = stmt.executeQuery(sql);
            while (rs.next()) {
                m.addElement(rs.getString("productname"));
                System.out.println("");
            }
            productList.setModel(m);
        } catch (SQLException ex) {
            Logger.getLogger(MakeBill.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
    public void getInfoComplete(){
        try {
            dtm=(DefaultTableModel) completeTable.getModel();
            dtm.setRowCount(0);
            JTableHeader header = completeTable.getTableHeader();
            header.setFont(new Font("Times New Roman", Font.BOLD, 20));
            DefaultTableCellRenderer d = ((DefaultTableCellRenderer) completeTable.getTableHeader().getDefaultRenderer());
            d.setHorizontalAlignment(JLabel.LEFT);
            String sql="Select s.numberPlate,b.ownername from service as s,bikeinfo as b where s.numberplate=b.numberplate and s.status='Completed' and s.servicedate=current_date() and s.billing='not billed' ";
            rs=stmt.executeQuery(sql);
            while(rs.next()){
                
                String numberplate=rs.getString("numberPlate");
                String name=rs.getString("ownerName");
                System.out.println(numberplate);
                System.out.println(name);
                dtm=(DefaultTableModel) completeTable.getModel();
                String []list={numberplate,name};
                dtm.addRow(list);
            }
        } catch (SQLException ex) {
            Logger.getLogger(MakeBill.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        printButton = new javax.swing.JButton();
        txtbill = new javax.swing.JTextPane();
        jDialog2 = new javax.swing.JDialog();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        ownerName = new javax.swing.JLabel();
        contact = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        model = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        numberPlate = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        totalPrice = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        a = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        detailProblem = new javax.swing.JTextArea();
        jScrollPane8 = new javax.swing.JScrollPane();
        info = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        numberPlateTextField = new javax.swing.JTextField();
        contactTextField = new javax.swing.JTextField();
        ownerNameTextField = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        productTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        productName = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        quantity = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        price = new javax.swing.JTextField();
        addButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        productList = new javax.swing.JList();
        jLabel12 = new javax.swing.JLabel();
        searchBar = new javax.swing.JTextField();
        generateButton = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        total = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        amountLabel = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        completeTable = new javax.swing.JTable();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        detailProblems = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        billTable = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        jDialog1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel1.setText("Bill");
        jLabel1.setToolTipText("");

        printButton.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        printButton.setText("Print");
        printButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printButtonActionPerformed(evt);
            }
        });

        txtbill.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtbill.setToolTipText("");
        txtbill.setFocusTraversalPolicy(null);
        txtbill.setFocusable(false);
        txtbill.setRequestFocusEnabled(false);

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialog1Layout.createSequentialGroup()
                        .addGap(278, 278, 278)
                        .addComponent(printButton, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDialog1Layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(txtbill, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(99, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialog1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(275, 275, 275))
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtbill, javax.swing.GroupLayout.PREFERRED_SIZE, 641, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(printButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setText("Owner Name");

        ownerName.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        ownerName.setText("Owner Name");

        contact.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        contact.setText("Owner Name");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel6.setText("Contact");

        model.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        model.setText("Owner Name");

        jLabel15.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel15.setText("Model");

        jLabel21.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel21.setText("Number Plate");

        numberPlate.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        numberPlate.setText("Owner Name");

        jLabel24.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel24.setText("Bill Info");

        date.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        date.setText("Owner Name");

        jLabel26.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel26.setText("Date");

        totalPrice.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        totalPrice.setText("Owner Name");

        jLabel28.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel28.setText("Total Price");

        jLabel29.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel29.setText("Email");

        email.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        email.setText("Owner Name");

        a.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        a.setText("Detail Problems");

        detailProblem.setEditable(false);
        detailProblem.setBackground(new java.awt.Color(204, 204, 204));
        detailProblem.setColumns(20);
        detailProblem.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        detailProblem.setLineWrap(true);
        detailProblem.setRows(5);
        jScrollPane7.setViewportView(detailProblem);

        info.setEditable(false);
        info.setBackground(new java.awt.Color(204, 204, 204));
        info.setColumns(20);
        info.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        info.setLineWrap(true);
        info.setRows(5);
        info.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jScrollPane8.setViewportView(info);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE))
                            .addComponent(a, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(142, 142, 142)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
                                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                            .addComponent(totalPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(numberPlate, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(167, 167, 167)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ownerName, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(contact, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(model, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ownerName, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(contact, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(model, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numberPlate, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(90, 90, 90))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(a, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36))
        );

        javax.swing.GroupLayout jDialog2Layout = new javax.swing.GroupLayout(jDialog2.getContentPane());
        jDialog2.getContentPane().setLayout(jDialog2Layout);
        jDialog2Layout.setHorizontalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDialog2Layout.setVerticalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1233, 723));
        setRequestFocusEnabled(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(1220, 700));
        jPanel1.setPreferredSize(new java.awt.Dimension(1220, 700));
        jPanel1.setRequestFocusEnabled(false);

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        jTabbedPane1.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel2.setPreferredSize(new java.awt.Dimension(1224, 703));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel7.setText("Owner Name");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel9.setText("Contact");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel10.setText("Bike Number-Plate");

        numberPlateTextField.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        numberPlateTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberPlateTextFieldActionPerformed(evt);
            }
        });
        numberPlateTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                numberPlateTextFieldKeyReleased(evt);
            }
        });

        contactTextField.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        ownerNameTextField.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        ownerNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ownerNameTextFieldActionPerformed(evt);
            }
        });

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        productTable.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        productTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product Name", "Quantity", "Price ", "Amount"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(productTable);
        if (productTable.getColumnModel().getColumnCount() > 0) {
            productTable.getColumnModel().getColumn(0).setMinWidth(130);
        }

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setText("Product Name");

        productName.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        productName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productNameActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel8.setText("Quantity");

        quantity.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        quantity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                quantityKeyReleased(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel11.setText("Price");

        price.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        price.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceActionPerformed(evt);
            }
        });

        addButton.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        addButton.setText("Add");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        productList.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        productList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        productList.setMaximumSize(new java.awt.Dimension(10, 10));
        productList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                productListMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(productList);

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel12.setText("Product List");

        searchBar.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        searchBar.setText("Search...");
        searchBar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                searchBarFocusGained(evt);
            }
        });
        searchBar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBarActionPerformed(evt);
            }
        });
        searchBar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchBarKeyReleased(evt);
            }
        });

        generateButton.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        generateButton.setText("Generate");
        generateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateButtonActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel19.setText("Total");

        total.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel13.setText("Amount");

        amountLabel.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(quantity, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                            .addComponent(productName, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(price)
                            .addComponent(amountLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(searchBar, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(92, 92, 92)
                                .addComponent(generateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 27, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(productName, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(price, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                            .addComponent(amountLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(26, Short.MAX_VALUE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(86, 86, 86)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(generateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32))))))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchBar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel16.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel16.setText("Bill no:");

        completeTable.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        completeTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Number Plate", "Owner Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        completeTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                completeTableMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(completeTable);

        jLabel17.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel17.setText("Detail Problems");

        jScrollPane4.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        detailProblems.setColumns(20);
        detailProblems.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        detailProblems.setLineWrap(true);
        detailProblems.setRows(5);
        jScrollPane4.setViewportView(detailProblems);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(84, 84, 84)
                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel10))
                                .addGap(20, 20, 20)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(numberPlateTextField)
                                    .addComponent(ownerNameTextField)
                                    .addComponent(contactTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(73, 73, 73)
                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 3, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(numberPlateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(29, 29, 29)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ownerNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(contactTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(38, 38, 38)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Make Bill", jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        billTable.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        billTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Bill ID", "Service ID", "Name", "Number Plate", "Model", "Total Amount", "Date"
            }
        ));
        billTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane6.setViewportView(billTable);

        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });

        jButton1.setText("View Detail");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 1202, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 70, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 528, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("History", jPanel3);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 23, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 699, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 41, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1230, 740));

        setBounds(0, 0, 1233, 751);
    }// </editor-fold>//GEN-END:initComponents

    private void numberPlateTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberPlateTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numberPlateTextFieldActionPerformed

    private void numberPlateTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_numberPlateTextFieldKeyReleased
       
    }//GEN-LAST:event_numberPlateTextFieldKeyReleased

    private void ownerNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ownerNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ownerNameTextFieldActionPerformed

    private void productNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productNameActionPerformed

    private void priceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        DefaultTableModel dtm = (DefaultTableModel) productTable.getModel();
        System.out.println(dtm.getRowCount());
        if (dtm.getRowCount() == 0) {
            dtm.setRowCount(0);
        }
        String productName = this.productName.getText();
        String quantity = this.quantity.getText();
        String price = this.price.getText();
        int total = Integer.parseInt(price) * Integer.parseInt(quantity);
        String sTotal = String.valueOf(total);
        String[] list = {productName, quantity, price, sTotal};
        dtm.addRow(list);
        newTotal +=total;
        this.total.setText(String.valueOf(newTotal));
    }//GEN-LAST:event_addButtonActionPerformed

    private void productListMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productListMousePressed
        try {

            String productName = productList.getSelectedValue().toString();
            String sql = "Select * from product where productname='" + productName + "'";
            rs = stmt.executeQuery(sql);
            if (rs.first()) {
                if (evt.getClickCount() == 2) {
                    if(numberPlateTextField.getText().equals("")){
                                            JOptionPane.showMessageDialog(null, "Please Choose the Serviced bike first",     "", JOptionPane.ERROR_MESSAGE);
                    }else{
                    this.productName.setText(productName);;
                    price.setText(rs.getString("price"));
                    this.quantity.setText("");
                    this.amountLabel.setText("");
                    }
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(MakeBill.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_productListMousePressed

    private void searchBarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchBarFocusGained
        searchBar.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_searchBarFocusGained

    private void searchBarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchBarActionPerformed

    private void searchBarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchBarKeyReleased
        search();
    }//GEN-LAST:event_searchBarKeyReleased
    public void search() {
        m.removeAllElements();
        String sql = "Select productname from product where productname like '" + searchBar.getText() + "%'";
        try {
            rs = stmt.executeQuery(sql);
            while (rs.next()) {
                m.addElement(rs.getString("productname"));
            }
            productList.setModel(m);
        } catch (SQLException ex) {
            Logger.getLogger(MakeBill.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void completeTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_completeTableMouseClicked
        int row=completeTable.getSelectedRow();
        String data=completeTable.getModel().getValueAt(row,0).toString();
        System.out.println(data);
        try {
            String sql = "Select s.serviceid,b.ownername,b.contact,s.numberplate,s.detailproblems from service as s,bikeinfo as b where s.numberplate='"+ data+"' and b.numberplate='"+ data+"'";
            rs = stmt.executeQuery(sql);
            if (rs.first()) {
                System.out.println("true");
                if (evt.getClickCount() == 2) {
                    serviceId=rs.getInt("serviceid");
                    System.out.println(serviceId);
                    contactTextField.setText(rs.getString("contact"));
                    numberPlateTextField.setText(rs.getString("numberplate"));
                    ownerNameTextField.setText(rs.getString("ownername"));
                    System.out.println(rs.getString("detailproblems"));
                    detailProblems.setText(rs.getString("detailproblems"));
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(MakeBill.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_completeTableMouseClicked

    private void generateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateButtonActionPerformed
        DefaultTableModel dtm = (DefaultTableModel) productTable.getModel();
        System.out.println(dtm.getRowCount());
        if(dtm.getRowCount()==0){
            JOptionPane.showMessageDialog(null, "Please choose the product first",     "", JOptionPane.ERROR_MESSAGE);
        }else{
            bill();
            jDialog1.setSize(dmsn);
            jDialog1.setLocationRelativeTo(null);
            jDialog1.setVisible(true);
           
       }
    }//GEN-LAST:event_generateButtonActionPerformed
    public void store(){
        DefaultTableModel dtm = (DefaultTableModel) productTable.getModel();
        System.out.println(dtm.getRowCount());
        String []product=new String[dtm.getRowCount()];
        String []quantity=new String[dtm.getRowCount()];
        String []price=new String[dtm.getRowCount()];
        String []amount=new String[dtm.getRowCount()];
        System.out.println();
        for(int i=0;i<dtm.getRowCount();i++){
            product[i]=productTable.getModel().getValueAt(i, 0).toString();
            quantity[i]=productTable.getModel().getValueAt(i, 1).toString();
            price[i]=productTable.getModel().getValueAt(i, 2).toString();
            amount[i]=productTable.getModel().getValueAt(i, 3).toString();
        }
//            System.out.println(Arrays.toString(product));
            String products = String.join(",",product); 
            String quantitys = String.join(",",quantity); 
            String prices = String.join(",",price); 
            String amounts = String.join(",",amount); 
            System.out.println(products);
            System.out.println(quantitys);
            System.out.println(prices);
            System.out.println(amounts);
            String numberPlate=numberPlateTextField.getText();
            String totalPrice=total.getText();
            String ownername=ownerNameTextField.getText();
            String contact=contactTextField.getText();
            try {
                String sql1="Update service set billing='Done' where serviceId='"+serviceId+"'";
                int rs1=stmt.executeUpdate(sql1);
                String sql="Insert into makebill(serviceid,numberplate,ownername,contact,product,quantity,price,amount,totalprice) VALUES('"+serviceId+"','"+numberPlate+"','"+ownername+"','"+contact+"','"+products+"','"+quantitys+"','"+prices+"','"+amounts+"','"+totalPrice+"')";
                int rs=stmt.executeUpdate(sql);
            } catch (SQLException ex) {
                Logger.getLogger(FMakeBill.class.getName()).log(Level.SEVERE, null, ex);
            }
            System.out.println(serviceId);
    }
    public void bill()
    {
        txtbill.setText("");
         String total = this.total.getText();
        
          DefaultTableModel model = new DefaultTableModel();
        
        model = (DefaultTableModel)productTable.getModel();
        
         txtbill.setText(txtbill.getText() + "*****************************************************************\n");
         txtbill.setText(txtbill.getText() + "\t\t        D&D AUTO LINK                          \n");
         txtbill.setText(txtbill.getText() + "*****************************************************************\n\n");
         txtbill.setText(txtbill.getText() + "Contact:980-1006912\n\n");
         txtbill.setText(txtbill.getText() + "Email:dndyamaha@hotmail.com\n\n");
        
         //Heading
          txtbill.setText(txtbill.getText() + "Product" +"\t\t" + "Quantity" + "\t" + "Price" + "\t" + "Amount" + "\n\n"  );
          
          
          for(int i = 0; i < model.getRowCount(); i++)
          {
              
              String pname = (String)model.getValueAt(i, 0);
              String price = (String)model.getValueAt(i, 2);
              String quantity=(String)model.getValueAt(i, 1);
              String amount = (String)model.getValueAt(i, 3);
              System.out.println("Lenght="+pname.length());
              if(pname.length()>10){
                txtbill.setText(txtbill.getText() + pname.trim()  + " \t" + quantity  + "\t" +price + "\t" + amount  + "\n"  );
              }else{
                  txtbill.setText(txtbill.getText() + pname.trim()  + " \t\t" + quantity  + "\t" +price + "\t" + amount  + "\n"  );
              }
          }
          
          txtbill.setText(txtbill.getText() + "\n\n");    
          
          txtbill.setText(txtbill.getText() + "\t\t\t\t"  + "        Subtotal :" + total + "\n\n\n\n");
          txtbill.setText(txtbill.getText() + "*****************************************************************\n");
         txtbill.setText(txtbill.getText() + "\t\tTHANK YOU VISIT AGAIN                         \n");
         txtbill.setText(txtbill.getText() + "*****************************************************************\n\n");     
    }
    private void quantityKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_quantityKeyReleased
        String quantity = this.quantity.getText();
        if(this.quantity.getText().equals("")){
            amountLabel.setText("");
       }
else{
            String price = this.price.getText();
        int amount=Integer.parseInt(price) * Integer.parseInt(quantity);
        amountLabel.setText(String.valueOf(amount));
        }
    }//GEN-LAST:event_quantityKeyReleased
    public void getBillNumber() {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection(url, "root", "");
            stmt = con.createStatement();
            String sql = "Select * from makebill";
            rs = stmt.executeQuery(sql);
            if (rs.first() == false) {
                String sql1 = "ALTER TABLE makebill AUTO_INCREMENT=1";
                stmt.executeUpdate(sql1);
                jLabel16.setText("Bill ID: 1");
            } else {
                if (rs.last()) {
                   int newServiceId=rs.getInt("billnumber")+1;
                   jLabel16.setText("Bill ID: "+newServiceId);
                }
            }

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AddToRepairPage.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(AddToRepairPage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void printButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printButtonActionPerformed
        try {
            txtbill.print();
            jDialog1.dispose();
            store();
//            this.dispose();
            this.numberPlateTextField.setText("");
            ownerNameTextField.setText("");
            contactTextField.setText("");
            detailProblems.setText("");
            DefaultTableModel dtm=(DefaultTableModel) productTable.getModel();
            dtm.setRowCount(0);
            productName.setText("");
            quantity.setText("");
            price.setText("");
            amountLabel.setText("");
            searchBar.setText("Search...");
            total.setText("");
            getBillNumber();
            billData();
            getInfoComplete();
            newTotal=0;
//            HomePage h= new HomePage();
//            h.setVisible(true);
//            h.makeBill();
//            } catch (ClassNotFoundException ex) {
//                Logger.getLogger(FMakeBill.class.getName()).log(Level.SEVERE, null, ex);
//            } catch (SQLException ex) {
//                Logger.getLogger(FMakeBill.class.getName()).log(Level.SEVERE, null, ex);
            }
              catch (PrinterException ex) {
            Logger.getLogger(FMakeBill.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }//GEN-LAST:event_printButtonActionPerformed

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
        try {
            String sql = "Select  m.serviceid,m.billnumber,m.ownername,b.bikemodel,m.totalprice,m.date,m.numberplate from bikeinfo as b,makebill as m where m.numberplate=b.numberplate and m.ownername like '" + jTextField1.getText() + "%' "; //e.g P type garepachi pachadi j bhaye ni huncha bhaneko 
            stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery(sql);
            DefaultTableModel dtm = (DefaultTableModel) billTable.getModel();
            dtm.setRowCount(0);//Removing all the row in Jtable
            while (rs.next()) {
                String billnumber=rs.getString("m.billnumber");
                String serviceid=rs.getString("m.serviceid");
                String name = rs.getString("m.ownername");
                String model = rs.getString("b.bikemodel");
                String date = rs.getString("m.date");
                String totalprice = rs.getString("m.totalprice");
                String numberplate = rs.getString("m.numberplate");
                System.out.println(numberplate);
                String data[] = {billnumber,serviceid,name,model,numberplate,totalprice,date};
                System.out.println(Arrays.toString(data));
                dtm.addRow(data);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jTextField1KeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            jDialog2.setSize(970,889);
            jDialog2.setLocationRelativeTo(null);
            jDialog2.setVisible(true);
            int row=billTable.getSelectedRow();
            if (row == -1) {
            row = 0;
        }
        String sdata = billTable.getModel().getValueAt(row, 0).toString();
        int data = Integer.parseInt(sdata);
        System.out.println(data);
//        String sserviceid = jTable1.getModel().getValueAt(row, 1).toString();
//        int serviceid = Integer.parseInt(sserviceid);
//        System.out.println(serviceid);
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection(url, "root", "");
            stmt = con.createStatement();
            info.setFocusable(false);
            detailProblem.setFocusable(false);
            if (con != null) {
                String sql = "Select m.date,m.totalprice,m.ownername,m.contact,b.email,b.bikemodel,m.product,m.quantity,m.price,m.amount,m.numberplate,s.detailproblems from makebill as m,service as s,bikeinfo as b where m.numberplate=b.numberplate and  m.serviceid=s.serviceid and m.billnumber="+ data;
                rs = stmt.executeQuery(sql);
                if (rs.first()) {
                    ownerName.setText(rs.getString("ownername"));
                    contact.setText(rs.getString("contact"));
                    email.setText(rs.getString("email"));
                    model.setText(rs.getString("bikemodel"));
                    numberPlate.setText(rs.getString("numberplate"));
                    detailProblem.setText(rs.getString("detailproblems"));
                    contact.setText(rs.getString("contact"));
                    date.setText(rs.getString("date"));
                    totalPrice.setText(rs.getString("totalprice"));
                    String[] product=rs.getString("product").split(",");
                    System.out.println(Arrays.toString(product));
                    String[] quantity=rs.getString("quantity").split(",");
                    String[] price=rs.getString("price").split(",");
                    info.setText("");
                    info.setText(info.getText() + "Product" +"\t" + "Quantity" + "\t" + "Price"  + "\n\n"  );
                    for(int i=0;i<product.length;i++){
                        info.setText(info.getText() + product[i].trim()+"\t" + quantity[i].trim() + "\t" + price[i].trim()  + "\n"  );
                    }
//                    jTextArea2.setEditable(false);
//                    jTextArea2.setText(rs.getString("detailproblems"));
//                    totalkmLabel.setText(rs.getString("totalkm"));
//                    status.setText(rs.getString("status"));
                }
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AddToRepairPage.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(AddToRepairPage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel a;
    private javax.swing.JButton addButton;
    private javax.swing.JLabel amountLabel;
    private javax.swing.JTable billTable;
    private javax.swing.JTable completeTable;
    private javax.swing.JLabel contact;
    private javax.swing.JTextField contactTextField;
    private javax.swing.JLabel date;
    private javax.swing.JTextArea detailProblem;
    private javax.swing.JTextArea detailProblems;
    private javax.swing.JLabel email;
    private javax.swing.JButton generateButton;
    private javax.swing.JTextArea info;
    private javax.swing.JButton jButton1;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel model;
    private javax.swing.JLabel numberPlate;
    private javax.swing.JTextField numberPlateTextField;
    private javax.swing.JLabel ownerName;
    private javax.swing.JTextField ownerNameTextField;
    private javax.swing.JTextField price;
    private javax.swing.JButton printButton;
    private javax.swing.JList productList;
    private javax.swing.JTextField productName;
    private javax.swing.JTable productTable;
    private javax.swing.JTextField quantity;
    private javax.swing.JTextField searchBar;
    private javax.swing.JLabel total;
    private javax.swing.JLabel totalPrice;
    private javax.swing.JTextPane txtbill;
    // End of variables declaration//GEN-END:variables
}
