/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bikeservicecenterproject;

import java.awt.Dimension;
import java.awt.Font;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.scene.paint.Color;
import javax.swing.*;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author パワーPower
 */
public class Register extends javax.swing.JInternalFrame {

    Connection con;
    Statement stmt;
    String user;
    String pw;
    DefaultTableModel tblmodel;
    String url = "jdbc:mysql://localhost:3306/bikeservicecenter";
    Dimension dialogSize = new Dimension(960, 742);

    /**
     * /**
     * Creates new form Register
     */
    public Register() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI) this.getUI();
        ui.setNorthPane(null);
        try {
            jTable1.setRowHeight(jTable1.getRowHeight() + 20);
            retriveData();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Register.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Register.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void retriveData() throws ClassNotFoundException, SQLException {
        tblmodel = (DefaultTableModel) jTable1.getModel();
        tblmodel.setRowCount(0);
        Class.forName("com.mysql.jdbc.Driver");
        con = DriverManager.getConnection(url, "root", "");
        if (con != null) {
            
            jTable1.setShowGrid(true);
            jTable1.setGridColor(java.awt.Color.BLACK);
            System.out.println("Database connected");
            stmt = con.createStatement();
            String sql = "Select ownername,bikemodel,contact,email,numberplate from bikeinfo order by ownername";
            ResultSet rs = stmt.executeQuery(sql);
//            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
            JTableHeader header = jTable1.getTableHeader();
            header.setFont(new Font("Times New Roman", Font.BOLD, 24));
            DefaultTableCellRenderer d = ((DefaultTableCellRenderer) jTable1.getTableHeader().getDefaultRenderer());
            d.setHorizontalAlignment(JLabel.LEFT);
            while (rs.next()) {
                String name = rs.getString("ownername");
                String model = rs.getString("bikemodel");
                String contact = rs.getString("contact");
                String email = rs.getString("email");
                String numberplate = rs.getString("numberplate");
                String data[] = {name, numberplate, model, email, contact};
                tblmodel.addRow(data);
            }
        } else {
            System.out.println("Database connection failed");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        viewDialog = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        bikeModelLabel = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        registerDateLabel = new javax.swing.JLabel();
        numberPlateLabel = new javax.swing.JLabel();
        bikeTypeLabel = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        contactLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        chasisNumberLabel = new javax.swing.JLabel();
        engineNumberLabel = new javax.swing.JLabel();
        ownerNameLabel = new javax.swing.JLabel();
        updateDialog = new javax.swing.JDialog();
        jPanel5 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        numberPlateTextField = new javax.swing.JTextField();
        ownerNameTextField = new javax.swing.JTextField();
        contactTextField = new javax.swing.JTextField();
        emailTextField = new javax.swing.JTextField();
        chasisNumberTextField = new javax.swing.JTextField();
        engineNumberTextField = new javax.swing.JTextField();
        update1 = new javax.swing.JButton();
        type = new javax.swing.JComboBox<>();
        model = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        recordPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        searchBar = new javax.swing.JTextField();
        updateButton = new javax.swing.JButton();
        detailButton = new javax.swing.JButton();
        registerationPanel = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        ownerName = new javax.swing.JTextField();
        bikeType = new javax.swing.JComboBox<>();
        bikeModel = new javax.swing.JComboBox<>();
        contact = new javax.swing.JTextField();
        numberPlate = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        chasisNumber = new javax.swing.JTextField();
        engineNumber = new javax.swing.JTextField();
        registerButton = new javax.swing.JButton();

        viewDialog.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        viewDialog.setBackground(new java.awt.Color(255, 255, 255));
        viewDialog.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                viewDialogWindowClosed(evt);
            }
        });
        viewDialog.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel3.setText("Number Plate");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel5.setText("Two wheeler Type");

        bikeModelLabel.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        bikeModelLabel.setText("Model");

        jLabel14.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel14.setText("Chasis number");

        jLabel15.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel15.setText("Contact");

        jLabel19.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel19.setText("Email");

        jLabel20.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel20.setText("Engine number");

        registerDateLabel.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        registerDateLabel.setText("Registered on:");

        numberPlateLabel.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        numberPlateLabel.setText("Number Plate");

        bikeTypeLabel.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        bikeTypeLabel.setText("Two wheeler Type");

        jLabel25.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel25.setText("Model");

        contactLabel.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        contactLabel.setText("Contact");

        emailLabel.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        emailLabel.setText("Email");

        chasisNumberLabel.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        chasisNumberLabel.setText("Chasis number");

        engineNumberLabel.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        engineNumberLabel.setText("Engine number");

        ownerNameLabel.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        ownerNameLabel.setText("Owner Name");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(160, 160, 160)
                        .addComponent(numberPlateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(jLabel5)
                        .addGap(160, 160, 160)
                        .addComponent(bikeTypeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(254, 254, 254)
                        .addComponent(bikeModelLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(254, 254, 254)
                        .addComponent(contactLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(254, 254, 254)
                        .addComponent(emailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(160, 160, 160)
                        .addComponent(chasisNumberLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(160, 160, 160)
                        .addComponent(engineNumberLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(308, 308, 308)
                        .addComponent(registerDateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(315, 315, 315)
                        .addComponent(ownerNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(115, 115, 115))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(ownerNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numberPlateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bikeTypeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bikeModelLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(contactLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chasisNumberLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(engineNumberLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(registerDateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        viewDialog.getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 710));

        updateDialog.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        updateDialog.setMinimumSize(new java.awt.Dimension(960, 742));

        jPanel5.setBackground(new java.awt.Color(204, 204, 204));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel13.setText("Number Plate");

        jLabel21.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel21.setText("Owner Name");

        jLabel22.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel22.setText("Two wheeler Type");

        jLabel23.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel23.setText("Chasis number");

        jLabel24.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel24.setText("Contact");

        jLabel26.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel26.setText("Email");

        jLabel27.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel27.setText("Engine number");

        jLabel28.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel28.setText("Model");

        numberPlateTextField.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        numberPlateTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberPlateTextFieldActionPerformed(evt);
            }
        });

        ownerNameTextField.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        contactTextField.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        emailTextField.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        chasisNumberTextField.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        engineNumberTextField.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        update1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        update1.setText("Update");
        update1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update1ActionPerformed(evt);
            }
        });

        type.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bike", "Scooter" }));
        type.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeActionPerformed(evt);
            }
        });

        model.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        model.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fz-V2", "R15", "Mt-15", "FZ-V#", "Fascino", "RayZr", "Alpha" }));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(432, 432, 432)
                        .addComponent(update1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel22)
                            .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE))
                        .addGap(174, 174, 174)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(engineNumberTextField)
                            .addComponent(chasisNumberTextField)
                            .addComponent(emailTextField)
                            .addComponent(contactTextField)
                            .addComponent(ownerNameTextField)
                            .addComponent(numberPlateTextField)
                            .addComponent(type, 0, 228, Short.MAX_VALUE)
                            .addComponent(model, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(247, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(numberPlateTextField)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ownerNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(type, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE))
                .addGap(33, 33, 33)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(model, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE))
                .addGap(33, 33, 33)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(contactTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chasisNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(engineNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addComponent(update1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        javax.swing.GroupLayout updateDialogLayout = new javax.swing.GroupLayout(updateDialog.getContentPane());
        updateDialog.getContentPane().setLayout(updateDialogLayout);
        updateDialogLayout.setHorizontalGroup(
            updateDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 960, Short.MAX_VALUE)
            .addGroup(updateDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        updateDialogLayout.setVerticalGroup(
            updateDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 750, Short.MAX_VALUE)
            .addGroup(updateDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1220, 700));
        setRequestFocusEnabled(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(1220, 700));
        jPanel1.setPreferredSize(new java.awt.Dimension(1220, 700));
        jPanel1.setRequestFocusEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1242, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jTabbedPane1.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        jTabbedPane1.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(1220, 700));

        recordPanel.setBackground(new java.awt.Color(255, 255, 255));

        jTable1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Owner Name", "Number Plate", "Model", "Email", "Contact"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setGridColor(new java.awt.Color(0, 0, 0));
        jTable1.setSelectionBackground(new java.awt.Color(204, 255, 204));
        jTable1.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(jTable1);

        searchBar.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        searchBar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBarActionPerformed(evt);
            }
        });
        searchBar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchBarKeyReleased(evt);
            }
        });

        updateButton.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        updateButton.setText("Update");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        detailButton.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        detailButton.setText("View details");
        detailButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detailButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout recordPanelLayout = new javax.swing.GroupLayout(recordPanel);
        recordPanel.setLayout(recordPanelLayout);
        recordPanelLayout.setHorizontalGroup(
            recordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(recordPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(detailButton, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addComponent(updateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 673, Short.MAX_VALUE)
                .addComponent(searchBar, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jScrollPane1)
        );
        recordPanelLayout.setVerticalGroup(
            recordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, recordPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(recordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(recordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(searchBar, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(detailButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(updateButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 609, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("Record", recordPanel);

        registerationPanel.setBackground(new java.awt.Color(255, 255, 255));

        jPanel6.setBackground(new java.awt.Color(204, 204, 204));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel7.setText("Contact");

        jLabel17.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel17.setText("Two-Wheeler type");

        jLabel18.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel18.setText("Bike model");

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel8.setText("Bike Number Plate");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel9.setText("Chasis number");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel10.setText("Email");

        jLabel16.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel16.setText("Owner Name");

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel11.setText("Engine number");

        ownerName.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        ownerName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ownerNameActionPerformed(evt);
            }
        });

        bikeType.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        bikeType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "    ", "Scooter", "Bike" }));
        bikeType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bikeTypeActionPerformed(evt);
            }
        });

        bikeModel.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        bikeModel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bikeModelActionPerformed(evt);
            }
        });

        contact.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        contact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactActionPerformed(evt);
            }
        });

        numberPlate.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        numberPlate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                numberPlateFocusLost(evt);
            }
        });
        numberPlate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberPlateActionPerformed(evt);
            }
        });

        email.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });

        chasisNumber.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        chasisNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chasisNumberActionPerformed(evt);
            }
        });

        engineNumber.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        registerButton.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        registerButton.setText("Register");
        registerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel6Layout.createSequentialGroup()
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(1, 1, 1))
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(registerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ownerName, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bikeType, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bikeModel, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(contact, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numberPlate, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(engineNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chasisNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(202, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(numberPlate, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(bikeType, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(bikeModel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(contact, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(ownerName, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(chasisNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(engineNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65)))
                .addGap(38, 38, 38)
                .addComponent(registerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout registerationPanelLayout = new javax.swing.GroupLayout(registerationPanel);
        registerationPanel.setLayout(registerationPanelLayout);
        registerationPanelLayout.setHorizontalGroup(
            registerationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registerationPanelLayout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(195, Short.MAX_VALUE))
        );
        registerationPanelLayout.setVerticalGroup(
            registerationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registerationPanelLayout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Registeration", registerationPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 719, Short.MAX_VALUE)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setBounds(0, 0, 1233, 723);
    }// </editor-fold>//GEN-END:initComponents

    private void searchBarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBarActionPerformed
        searchBar.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_searchBarActionPerformed

    private void searchBarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchBarKeyReleased
        // TODO add your handling code here:
        search(jTable1);
    }//GEN-LAST:event_searchBarKeyReleased
    public void search(JTable jtable) {
        try {
            String sql = "Select  ownername,bikemodel,contact,email,numberplate from bikeinfo where ownername like '" + searchBar.getText() + "%' Order by ownername"; //e.g P type garepachi pachadi j bhaye ni huncha bhaneko 
            stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery(sql);
            DefaultTableModel dtm = (DefaultTableModel) jtable.getModel();
            dtm.setRowCount(0);//Removing all the row in Jtable
            while (rs.next()) {
                String name = rs.getString("ownername");
                String model = rs.getString("bikemodel");
                String contact = rs.getString("contact");
                String email = rs.getString("email");
                String numberplate = rs.getString("numberplate");
                String data[] = {name, numberplate, model, email, contact};
                tblmodel = (DefaultTableModel) jtable.getModel();
                tblmodel.addRow(data);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
//        jTable1.changeSelection(0, 0, false, false);
        int row = jTable1.getSelectedRow();
        if (row == -1) {
            row = 0;
        }
        String data = jTable1.getModel().getValueAt(row, 1).toString();
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection(url, "root", "");
            stmt = con.createStatement();
            if (con != null) {
                String sql1 = "Select * from bikeinfo where numberplate='" + data + "'";
                ResultSet rs = stmt.executeQuery(sql1);
                if (rs.first()) {
                    numberPlateTextField.setText(rs.getString(1));
                    ownerNameTextField.setText(rs.getString(2));
                    type.setSelectedItem(rs.getString(3));
                    model.setSelectedItem(rs.getString(4));
                    contactTextField.setText(rs.getString(5));
                    emailTextField.setText(rs.getString(6));
                    chasisNumberTextField.setText(rs.getString(7));
                    engineNumberTextField.setText(rs.getString(8));
                }
            } else {
                System.out.println("Database Not connected");
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(HomePage.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(HomePage.class.getName()).log(Level.SEVERE, null, ex);
        }
        updateDialog.setSize(dialogSize);
        updateDialog.setLocationRelativeTo(null);
        updateDialog.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_updateButtonActionPerformed

    private void detailButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detailButtonActionPerformed
        //        jTable1.changeSelection(0, 0, false, false);
        int row = jTable1.getSelectedRow();
        System.out.println(row);
        if (row == -1) {
            row = 0;
        }
        String data = jTable1.getModel().getValueAt(row, 1).toString();

        try {

            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection(url, "root", "");
            stmt = con.createStatement();
            if (con != null) {
                String sql = "Select * from bikeinfo where numberplate='" + data + "'";
                ResultSet rs = stmt.executeQuery(sql);
                if (rs.first()) {
                    numberPlateLabel.setText(rs.getString(1));
                    ownerNameLabel.setText(rs.getString(2) + "'s Detail");
                    bikeTypeLabel.setText(rs.getString(3));
                    bikeModelLabel.setText(rs.getString(4));
                    contactLabel.setText(rs.getString(5));
                    emailLabel.setText(rs.getString(6));
                    chasisNumberLabel.setText(rs.getString(7));
                    engineNumberLabel.setText(rs.getString(8));
                    registerDateLabel.setText("Rsgisterd on: " + rs.getString(9));
                }
            } else {
                System.out.println("Database Not connected");
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(HomePage.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(HomePage.class.getName()).log(Level.SEVERE, null, ex);
        }

        viewDialog.setSize(dialogSize);
        viewDialog.setLocationRelativeTo(null);
        viewDialog.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_detailButtonActionPerformed

    private void viewDialogWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_viewDialogWindowClosed
        System.out.println("true");
    }//GEN-LAST:event_viewDialogWindowClosed

    private void chasisNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chasisNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chasisNumberActionPerformed

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void numberPlateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberPlateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numberPlateActionPerformed

    private void numberPlateFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_numberPlateFocusLost
        try {
            String numberPlate = this.numberPlate.getText();
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection(url, "root", "");
            stmt = con.createStatement();
            String sql = "Select * from bikeinfo where numberplate='" + numberPlate + "'";
            ResultSet rs = stmt.executeQuery(sql);
            if (rs.first()) {
                JOptionPane.showMessageDialog(this, "Bike is already registered.", "Information", JOptionPane.INFORMATION_MESSAGE);
                this.numberPlate.setText("");
                this.numberPlate.requestFocusInWindow();
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Register.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Register.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_numberPlateFocusLost

    private void contactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contactActionPerformed

    private void bikeModelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bikeModelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bikeModelActionPerformed

    private void registerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerButtonActionPerformed
        try {
            Class.forName("com.mysql.jdbc.Driver");
            String ownername = ownerName.getText();
            String numberplate = numberPlate.getText();
            String biketype = bikeType.getSelectedItem().toString();
            String bikemodel = bikeModel.getSelectedItem().toString();
            String Contact = contact.getText();
            String Email = email.getText();
            String chasisnumber = chasisNumber.getText();
            String enginenumber = engineNumber.getText();
            System.out.println(ownername + " " + numberplate + " " + biketype + " " + bikemodel + " " + Contact + " " + Email + " " + chasisnumber + " " + enginenumber);
            con = DriverManager.getConnection(url, "root", "");
            if (con != null) {
                System.out.println("Database connected");
                stmt = con.createStatement();
                String sql = "Insert into bikeinfo (numberplate,ownername,biketype,bikemodel,contact,email,chasisnumber,enginenumber) Values('" + numberplate + "','" + ownername + "','" + biketype + "','" + bikemodel + "','" + Contact + "','" + Email + "','" + chasisnumber + "','" + enginenumber + "')";
                int result;
                result = stmt.executeUpdate(sql);
                if (result != -1) {
                    JOptionPane.showMessageDialog(this, "Register message", "Resgistered", JOptionPane.INFORMATION_MESSAGE);
//                    this.dispose();
//                    this.removeAll();
                    ownerName.setText("");
                    numberPlate.setText("");
                    bikeType.setSelectedIndex(0);
                    bikeModel.setSelectedIndex(-1);
                    contact.setText("");
                    email.setText("");
                    chasisNumber.setText("");
                    engineNumber.setText("");
                    retriveData();
                    jTabbedPane1.setSelectedIndex(0);
                    
//                    this.add(new Register()).setVisible(true);
                } else {
                    JOptionPane.showMessageDialog(null, "Sorry couldnt Register", "Register messahe", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                System.out.println("Database connection failed");
            }

            //        JOptionPane j=new JOptionPane();
            //        int res = JOptionPane.showOptionDialog(this, "Registered", "Registered Message", JOptionPane.DEFAULT_OPTION,
            //        JOptionPane.INFORMATION_MESSAGE, null, null, null);
            //        if(res!=-1){
            //        this.dispose();
            //        new HomePage().setVisible(true);
            //        }
        } catch (SQLException ex) {
            Logger.getLogger(HomePage.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(HomePage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_registerButtonActionPerformed

    private void bikeTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bikeTypeActionPerformed
        // TODO add your handling code here:
        if (bikeType.getSelectedItem().toString().equals("Bike")) {
            bikeModel.removeAllItems();
            bikeModel.addItem("Fz-V2");
            bikeModel.addItem("R15");
            bikeModel.addItem("Mt-15");
            bikeModel.addItem("FZ-V3");
        }
        if (bikeType.getSelectedItem().toString().equals("Scooter")) {
            bikeModel.removeAllItems();
            bikeModel.addItem("Fascino");
            bikeModel.addItem("RayZr");
            bikeModel.addItem("Alpha");
        }
        if (bikeType.getSelectedItem().toString().equals(" ")) {
            bikeModel.setSelectedIndex(-1);
        }
    }//GEN-LAST:event_bikeTypeActionPerformed

    private void ownerNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ownerNameActionPerformed

    }//GEN-LAST:event_ownerNameActionPerformed

    private void update1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update1ActionPerformed
        try {
            int row = jTable1.getSelectedRow();
            if (row == -1) {
                row = 0;
            }
            String data = jTable1.getModel().getValueAt(row, 1).toString();
            System.out.println(data);

            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection(url, "root", "");
            if (con != null) {
                if (!ownerNameTextField.getText().isEmpty()) {
                    stmt = con.createStatement();
                    String sql = "Update bikeinfo set ownername='" + ownerNameTextField.getText() + "' where numberplate='" + data + "'";
                    int result = stmt.executeUpdate(sql);
                    if (result != -1) {
                        System.out.println("Updated");
                    }
                }
                if (!contactTextField.getText().isEmpty()) {
                    stmt = con.createStatement();
                    String sql = "Update bikeinfo set contact='" + contactTextField.getText() + "' where numberplate='" + data + "'";
                    int result = stmt.executeUpdate(sql);
                    if (result != -1) {
                        System.out.println("Updated");
                    }
                }
                if (!emailTextField.getText().isEmpty()) {
                    stmt = con.createStatement();
                    String sql = "Update bikeinfo set email='" + emailTextField.getText() + "' where numberplate='" + data + "'";
                    int result = stmt.executeUpdate(sql);
                    if (result != -1) {
                        System.out.println("Updated");
                    }
                }
                if (!chasisNumberTextField.getText().isEmpty()) {
                    stmt = con.createStatement();
                    String sql = "Update bikeinfo set chasisnumber='" + chasisNumberTextField.getText() + "' where numberplate='" + data + "'";
                    int result = stmt.executeUpdate(sql);
                    if (result != -1) {
                        System.out.println("Updated");
                    }
                }
                if (!engineNumberTextField.getText().isEmpty()) {
                    stmt = con.createStatement();
                    String sql = "Update bikeinfo set enginenumber='" + engineNumberTextField.getText() + "' where numberplate='" + data + "'";
                    int result = stmt.executeUpdate(sql);
                    if (result != -1) {
                        System.out.println("Updated");
                    }
                }

                if (!numberPlateTextField.getText().isEmpty()) {
                    stmt = con.createStatement();
                    String sql = "Update bikeinfo set numberplate='" + numberPlateTextField.getText() + "' where numberplate='" + data + "'";
                    int result = stmt.executeUpdate(sql);
                    if (result != -1) {
                        System.out.println("Updated");
                    }
                }
                if(!type.getSelectedItem().toString().isEmpty()){
                     stmt = con.createStatement();
                    String sql = "Update bikeinfo set biketype='" + type.getSelectedItem().toString()+ "' where numberplate='" + data + "'";
                    int result = stmt.executeUpdate(sql);
                    if (result != -1) {
                        System.out.println("Updated");
                    }
                }
                if(!model.getSelectedItem().toString().isEmpty()){
                     stmt = con.createStatement();
                    String sql = "Update bikeinfo set bikemodel='" + model.getSelectedItem().toString()+ "' where numberplate='" + data + "'";
                    int result = stmt.executeUpdate(sql);
                    if (result != -1) {
                        System.out.println("Updated");
                    }
                }
                retriveData();
            }
            updateDialog.dispose();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(HomePage.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(HomePage.class.getName()).log(Level.SEVERE, null, ex);
        }// TODO add your handling code here:
    }//GEN-LAST:event_update1ActionPerformed

    private void numberPlateTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberPlateTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numberPlateTextFieldActionPerformed

    private void typeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeActionPerformed
        if (type.getSelectedItem().toString().equals("Bike")) {
            model.removeAllItems();
            model.addItem("Fz-V2");
            model.addItem("R15");
            model.addItem("Mt-15");
            model.addItem("FZ-V3");
        }
        if (type.getSelectedItem().toString().equals("Scooter")) {
            model.removeAllItems();
            model.addItem("Fascino");
            model.addItem("RayZr");
            model.addItem("Alpha");
        }
        if (type.getSelectedItem().toString().equals("")) {
            model.removeAllItems();
        }
    }//GEN-LAST:event_typeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> bikeModel;
    private javax.swing.JLabel bikeModelLabel;
    private javax.swing.JComboBox<String> bikeType;
    private javax.swing.JLabel bikeTypeLabel;
    private javax.swing.JTextField chasisNumber;
    private javax.swing.JLabel chasisNumberLabel;
    private javax.swing.JTextField chasisNumberTextField;
    private javax.swing.JTextField contact;
    private javax.swing.JLabel contactLabel;
    private javax.swing.JTextField contactTextField;
    private javax.swing.JButton detailButton;
    private javax.swing.JTextField email;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JTextField engineNumber;
    private javax.swing.JLabel engineNumberLabel;
    private javax.swing.JTextField engineNumberTextField;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox<String> model;
    private javax.swing.JTextField numberPlate;
    private javax.swing.JLabel numberPlateLabel;
    private javax.swing.JTextField numberPlateTextField;
    private javax.swing.JTextField ownerName;
    private javax.swing.JLabel ownerNameLabel;
    private javax.swing.JTextField ownerNameTextField;
    private javax.swing.JPanel recordPanel;
    private javax.swing.JButton registerButton;
    private javax.swing.JLabel registerDateLabel;
    private javax.swing.JPanel registerationPanel;
    private javax.swing.JTextField searchBar;
    private javax.swing.JComboBox<String> type;
    private javax.swing.JButton update1;
    private javax.swing.JButton updateButton;
    private javax.swing.JDialog updateDialog;
    private javax.swing.JDialog viewDialog;
    // End of variables declaration//GEN-END:variables
}
